language: python

python:
  - "2.7"
  - "2.6"

virtualenv:
  system_site_packages: true

install:
    - CURRENT=$PWD
    - sudo pip install --upgrade pip
    - sudo apt-get install python-numpy -y
    - sudo apt-get install python-scipy -y
    - sudo apt-get install python-matplotlib -y 
    - sudo apt-get install python-pandas -y
    - sudo apt-get install python-sympy -y
    - sudo apt-get install python-sklearn -y
    - sudo apt-get install python-matplotlib -y
    - sudo pip install networkx
    - sudo pip install pydicom
    - sudo pip install Cython
    - wget https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
    - tar -xzvf six-1.9.0.tar.gz
    - cd six-1.9.0
    - sudo python setup.py install
    - cd $CURRENT
    - wget https://pypi.python.org/packages/source/n/nibabel/nibabel-2.0.0.tar.gz
    - tar -xzvf nibabel-2.0.0.tar.gz
    - cd nibabel-2.0.0
    - sudo python setup.py install
    - sudo pip install nilearn
    - sudo pip install scikit-image
    - sudo apt-get install python-nose -y
    - cd $CURRENT/testing

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    - DISTRIB="ubuntu-no-matplotlib" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
      MATPLOTLIB_VERSION="1.1.1" SCIKIT_LEARN_VERSION="0.11"
      NIBABEL_VERSION="1.1.0"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="*" SCIPY_VERSION="*"
      MATPLOTLIB_VERSION="*" SCIKIT_LEARN_VERSION="*" COVERAGE="true"

# command to run tests
script: bash $CURRENT/testing/run_tests.sh


