language: python

python:
  - "2.7"
  - "2.6"

virtualenv:
  system_site_packages: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install numpy
 - pip install scipy
 - pip install scikit-learn
 - pip install nibabel
 - pip install nilearn
 - pip install pandas
 - pip install matplotlib
 - pip install scikit-image
 - cd vsoch/pybraincompare
 - python setup.py sdist
 - python setup.py install

env:
  global:
    - TEST_RUN_FOLDER="/testing/automatic" # folder where the tests are run from


# command to run tests
script:  
 - chmod u+x testing/run_tests.sh
 - bash testing/run_tests.sh


