language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

install:
    - source continuous_integration/install.sh

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
      MATPLOTLIB_VERSION="1.1.1" SCIKIT_LEARN_VERSION="0.11"
      NIBABEL_VERSION="1.1.0" SIX_VERSION="1.9.0"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
      NUMPY_VERSION="*" SCIPY_VERSION="*"
      MATPLOTLIB_VERSION="*" SCIKIT_LEARN_VERSION="*" COVERAGE="true"

script: 
    - python continuous_integration/show-python-packages-versions.py
    - bash $CURRENT/testing/run_tests.sh


