language: python

python:
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - sudo pip install --upgrade pip
    - sudo apt-get install python-numpy -y
    - sudo apt-get install python-scipy -y
    - sudo apt-get install python-matplotlib -y 
    - sudo apt-get install python-pandas -y
    - sudo apt-get install python-sympy -y
    - sudo apt-get install python-nose -y
    - sudo apt-get install python-sklearn -y
    - sudo apt-get install python-nibabel -y
    - sudo apt-get install python-matplotlib -y
    - sudo pip install nilearn
    - sudo pip install scikit-image

env:
  global:
    - TEST_RUN_FOLDER="testing/" # folder where the tests are run from


# command to run tests
script: bash testing/run_tests.sh


