language: python

python:
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --user-mirrors

env:
  global:
    - TEST_RUN_FOLDER="testing/automatic" # folder where the tests are run from


# command to run tests
script: bash testing/run_tests.sh


