language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install scikit-learn
 - pip install nibabel
 - pip install nilearn
 - pip install pandas
 - pip install matplotlib
 - pip install scikit-image

# command to run tests
script:  
 - chmod u+x testing/run_tests.sh
 - bash testing/run_tests.sh
