language: python

python:
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install --upgrade pip
    - sudo apt-get install python-numpy python-scipy python-matplotlib python-pandas python-sympy python-nose  python-sklearn python-nibabel python-matplotlib -y
    - pip install -U --user nilearn
    - pip install -U --user scikit-image

env:
  global:
    - TEST_RUN_FOLDER="testing/" # folder where the tests are run from


# command to run tests
script: bash testing/run_tests.sh


