language: python

python:
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - apt-get install python-numpy python-scipy python-matplotlib python-pandas python-sympy python-nose
    - pip install scikit-learn
    - pip install nibabel
    - pip install nilearn
    - pip install scikit-image

env:
  global:
    - TEST_RUN_FOLDER="testing/automatic" # folder where the tests are run from


# command to run tests
script: bash testing/run_tests.sh


