language: python

python:
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - CURRENT=$PWD
    - sudo pip install --upgrade pip
    - sudo apt-get install python-numpy -y
    - sudo apt-get install python-scipy -y
    - sudo apt-get install python-matplotlib -y 
    - sudo apt-get install python-pandas -y
    - sudo apt-get install python-sympy -y
    - sudo apt-get install python-nose -y
    - sudo apt-get install python-sklearn -y
    - sudo apt-get install python-matplotlib -y
    - sudo pip install networkx
    - wget https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
    - tar -xzvf six-1.9.0.tar.gz
    - cd six-1.9.0
    - sudo python setup.py install
    - cd $CURRENT
    - wget https://pypi.python.org/packages/source/n/nibabel/nibabel-2.0.0.tar.gz
    - tar -xzvf nibabel-2.0.0.tar.gz
    - cd nibabel-2.0.0
    - sudo python setup.py install
    - sudo pip install nilearn
    - sudo pip install scikit-image
    - cd $CURRENT/testing

#env:
#  global:
#    - TEST_RUN_FOLDER="testing/" # folder where the tests are run from

# command to run tests
script: bash $CURRENT/testing/run_tests.sh


